### ISSUE TITLE
Syntax Error In Line 13

### ISSUE THREAD

**Issue by florian-poschlod** [tobloef/glitch-tool#2]
Output:
python glitch_tool.py -i img.jpg -m reverse -o /corrupt
  File "glitch_tool.py", line 13
    outPath = f"{args.outdir}{filename}_m={args.mode}_b={bytesTochange}_s={seed}_n={fileNum}_i={iteration}{extension}"
                                                                                                                     ^
SyntaxError: invalid syntax

**Comment by tobloef** [comment]
I reckon it has something do to with the Python version you're using. Closing since the issue is so old.
